stub pagefind
https://pagefind.app/docs/

I'm following this. I currently get this error, which is not mentioned at all in the docs

Running Pagefind v0.12.0 (Extended)
Running from: "/Users/lim/CYF/Repos/curriculum"
Source:       "public"
Bundle Directory:  "_pagefind"

[Walking source directory]
Found 279 files matching **/*.{html}

[Parsing files]
Did not find a data-pagefind-body element on the site.
↳ Indexing all <body> elements on the site.

[Reading languages]
Discovered 0 languages: 

[Building search indexes]
Total: 
  Indexed 0 languages
  Indexed 0 pages
  Indexed 0 words
  Indexed 0 filters
  Indexed 0 sorts
Error: Pagefind wasn't able to build an index. 
Most likely, the directory passed to Pagefind was empty or did not contain any html files.